package io.carrie.employee.employee.dtos;

import jakarta.validation.constraints.*;

import lombok.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateEmployeeDTO {

    @NotBlank
    @Pattern(regexp = "^[a-zA-Z]{2,30}$", message = "Invalid First name.")
    private String firstName;

    @NotBlank
    @Pattern(regexp = "^[a-zA-Z]{2,30}$", message = "Invalid Last name.")
    private String lastName;

    @NotBlank
    @Email
    private String email;

    @NotBlank
    @Pattern(regexp = "^\\+?\\d{1,3}(\\s\\d{3}){2,3}$", message = "Invalid phone number.")
    private String phone;

    private String address;

    // NOTE - constructors, getters & setters are generated by Lombok
}
