package io.carrie.employee.employee.dtos;

import jakarta.validation.constraints.*;

import lombok.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateEmployeeDTO {

    @NotBlank
    @Pattern(regexp = "^^[\\p{L} .'-]{2,30}$", message = "Enter valid first name.")
    private String firstName;

    @NotBlank
    @Pattern(regexp = "^[a-zA-Z\\s\\-']{2,30}$", message = "Enter valid last name (letters, spaces, hyphens, apostrophes).")
    private String lastName;

    @NotBlank
    @Email
    private String email;

    @NotBlank
    @Pattern(regexp = "^\\+?[0-9\\s\\-()]{8,20}$", message = "Invalid phone number. Use digits, spaces, dashes, parentheses, and optional leading '+'.")
    private String phone;

    private String address;

    // NOTE - constructors, getters & setters are generated by Lombok
}
