package io.carrie.employee.employee.dtos;

import jakarta.validation.constraints.*;

import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UpdateEmployeeDTO {

    // NOTE - all these fields are optional

    @Pattern(regexp = "^[\\p{L} .'-]{2,30}$", message = "Enter valid first name.")
    private String firstName;

    @Pattern(regexp = "^[a-zA-Z\\s\\-']{2,30}$", message = "Enter valid last name (letters, spaces, hyphens, apostrophes).")
    private String lastName;

    @Email
    private String email;

    @Pattern(regexp = "^\\+?[0-9\\s\\-()]{8,20}$", message = "Invalid phone number. Use digits, spaces, dashes, parentheses, and optional leading '+'.")
    private String phone;

    private String address;

    // NOTE - constructors, getters & setters are generated by Lombok
}
