package io.carrie.employee.employee.dtos;

import jakarta.validation.constraints.*;

import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UpdateEmployeeDTO {

    // NOTE - all these fields are optional

    @Pattern(regexp = "^[a-zA-Z]{2,30}$", message = "Enter valid first name.")
    private String firstName;

    @Pattern(regexp = "^[a-zA-Z]{2,30}$", message = "Enter valid last name.")
    private String lastName;

    @Email
    private String email;

    @Pattern(regexp = "^\\+?\\d{7,15}$", message = "Invalid phone number.")
    private String phone;

    private String address;

    // NOTE - constructors, getters & setters are generated by Lombok
}
