package io.carrie.employee.department;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import io.carrie.employee.contract.Contract;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data // getters and setters generated by Lombok
@NoArgsConstructor
@AllArgsConstructor

@Entity
@Table(name = "departments")
public class Department {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    @NotBlank(message = "Department name cannot be blank")
    private String name;

    @OneToMany(mappedBy = "department")
    @JsonIgnoreProperties({ "department", "contract" })
    private List<Contract> contracts;

}
