package io.carrie.employee.contract.dtos;

import java.math.BigDecimal;
import org.springframework.format.annotation.DateTimeFormat;
import jakarta.validation.constraints.*;
import lombok.*;

@Data // getters and setters generated by Lombok
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CreateContractDTO {

    @NotNull(message = "Employee ID is required")
    private Integer employeeId;

    private String department;

    @NotBlank(message = "Contract type is required")
    private String contractType;

    @DecimalMin(value = "0.0", inclusive = false, message = "Salary must be a positive number")
    private BigDecimal salaryAmount;

    @Max(value = 50, message = "Hours per week can't exceed 50")
    private Integer hoursPerWeek;

    // Convert local dates from ISO string date

    @NotNull(message = "Start date is required")
    @DateTimeFormat
    private String startDate;

    @DateTimeFormat
    // @ValidDateRange //TODO - check endDate is not before startDate
    private String endDate;

}
