package io.carrie.employee.employee;

import io.carrie.employee.contract.Contract;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.*;

@Data // getters and setters generated by Lombok
@NoArgsConstructor
@AllArgsConstructor
@Builder

@Entity
@Table(name = "employees")
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column
    private String firstName;

    @Column
    private String lastName;

    @Column(unique = true)
    private String email;

    @Column
    private String phone; // string is to keep original format

    @Column
    private String address; // can create dto for this later if needed

    @OneToMany(mappedBy = "employee", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties({ "employee", "contract" })
    private List<Contract> contracts;

    // NOTE - getters and setters, constructors are all generated by Lombok

    // Custom business logic method - not generated by Lombok
    // todo - get isActive (or last isActive) contract

}