package io.carrie.employee.employee;

import io.carrie.employee.contract.Contract;
import io.carrie.employee.employee.enums.EmployeeStatus;

import java.time.LocalDate;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.*;

// Lombok
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString

@Entity
@Table(name = "employees")
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column
    private String firstName;

    @Column
    private String lastName;

    @Column(unique = true)
    private String email;

    @Column
    private String phone; // keep original format

    @Column
    private String address; // dto validation later if needed

    @OneToMany(mappedBy = "employee", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    // Prevent circular references
    @JsonIgnoreProperties({ "employee", "contract" })
    @ToString.Exclude
    @Getter(AccessLevel.NONE) // use custom getters below
    @Setter(AccessLevel.PACKAGE) // Allow JPA access but not public
    private List<Contract> contracts;

    // NOTE - basic getters and setters, constructors are all generated by Lombok

    // SECTION - Custom business logic: contract access methods

    public EmployeeStatus getStatus() {
        if (!hasActiveContract())
            return EmployeeStatus.INACTIVE;
        if (getContractCount() == 1)
            return EmployeeStatus.NEW_HIRE;
        return EmployeeStatus.ACTIVE;
    }

    public boolean hasActiveContract() {
        // eg. use to check active employees in our company
        return getAllContracts().stream()
                .anyMatch(Contract::isActive);
    }

    public LocalDate getContractEndDate() {
        // eg. check if new contract needs renewal
        return getLatestContract() != null ? getLatestContract().getEndDate() : null;
    }

    public int getContractCount() {
        // eg. check if employee is new
        return getAllContracts().size();
    }

    // SECTION Private helper methods
    // provides security and encapsulation (eg. admin access only)

    private List<Contract> getAllContracts() {
        return (contracts != null ? contracts : List.<Contract>of()).stream()
                .sorted((c1, c2) -> c2.getStartDate().compareTo(c1.getStartDate())) // Latest first
                .toList();
    }

    private List<Contract> getActiveContracts() {
        return getAllContracts().stream()
                .filter(Contract::isActive)
                .toList();
    }

    private Contract getLatestContract() {
        // Get the most recent contract (active or inactive)
        return getAllContracts().stream()
                .findFirst()
                .orElse(null);
    }
}