---
config:
  layout: elk
  theme: neutral
  look: neo
---
flowchart TD
 subgraph s2["ADD EMPLOYEE"]
        C1@{ label: "User clicks 'Add Employee'" }
        C2["Show create form"]
        C3["User submits form"]
        C4["POST /employees"]
        C5["Return new employee data"]
        C6["Show success / update list"]
  end
 subgraph s4["DELETE EMPLOYEE"]
        E1@{ label: "User clicks 'Delete'" }
        E2["Show confirmation popup"]
        E3["User confirms"]
        E4["DELETE /employees/:id"]
        E5["Return 204 No Content"]
        E6["Remove from UI and show success"]
  end
 subgraph s1["VIEW EMPLOYEE LIST"]
        A1@{ label: "User clicks 'Employees' nav link" }
        A2["GET /employees"]
        A3["Return paginated employee list"]
        A4["Render employee list in UI"]
  end
 subgraph s5["VIEW EMPLOYEE RECORD"]
        B1["User clicks employee from list"]
        B2["GET /employees/:id"]
        B3["Return employee details"]
        B4["Render employee profile view"]
  end
 subgraph s3["EDIT EMPLOYEE"]
        D1@{ label: "User clicks 'Edit' on profile" }
        D2["Show pre-filled form"]
        D3["User submits form"]
        D4["PUT /employees/:id"]
        D5["Return updated employee data"]
        D6["Show updated profile / list"]
  end
    A1 --> A2
    A2 --> A3
    A3 --> A4
    B1 --> B2
    B2 --> B3
    B3 --> B4
    C1 --> C2
    C2 --> C3
    C3 --> C4
    C4 --> C5
    C5 --> C6
    D1 --> D2
    D2 --> D3
    D3 --> D4
    D4 --> D5
    D5 --> D6
    E1 --> E2
    E2 --> E3
    E3 --> E4
    E4 --> E5
    E5 --> E6
    A1@{ shape: rect}
    C1@{ shape: rect}
    D1@{ shape: rect}
    E1@{ shape: rect}
     A1:::Pine
     A2:::api
     A3:::api
     A4:::Pine
     C1:::Pine
     C4:::api
     C5:::api
     C6:::Pine
     D1:::Pine
     D4:::api
     D5:::api
     D6:::Pine
     E1:::Pine
     E4:::api
     E5:::api
     E6:::Pine
     B1:::Pine
     B2:::api
     B3:::api
     B4:::Pine
    classDef api fill:#fdf6e3,stroke:#b58900,stroke-width:1px
    classDef Pine stroke-width:1px, stroke-dasharray:none, stroke:#254336, fill:#27654A, color:#FFFFFF
    style s4 stroke:#D50000
    style s2 stroke:#D50000
    style s1 stroke:#D50000
