name: Deploy React App to AWS S3 and CloudFront

on:
  push:
    branches: ["main"]
    paths: ["front-end/**"] # Only run if something in front-end changes

  pull_request:
    branches: ["main"]
    types: [closed]
    paths: ["front-end/**"]

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  id-token: write # Allows the workflow to obtain an ID token to authenticate with AWS securely
  contents: read # Grants permission to read the repository content (useful for actions like checking out code)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./front-end # React app folder

    steps:
      # Checks out the repository code to the runner machine
      - name: Checkout source
        uses: actions/checkout@v3

      # Installs all npm dependencies required to build the React app-
      - name: Install dependencies
        run: npm install

      # Builds the React app, creating a production-ready version in the 'dist' folder
      - name: Build React App
        run: npm run build

      # Configures AWS credentials for the workflow to interact with AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          #   double-check that this is needed
          #   role-session-name: GitHubActionsSession

      - name:
          Deploy to S3
          # upload index.html file to s3, if it already exists, replace it
          # Syncs the 'assets' directory from the 'dist' folder to the S3 bucket, deleting old files that no longer exist
        run: |
          aws s3 cp ./dist/index.html s3://${{ secrets.AWS_S3_BUCKET }}/index.html
          aws s3 sync ./dist/assets s3://${{ secrets.AWS_S3_BUCKET }}/assets --delete
        working-directory: front-end

      - name:
          Invalidate CloudFront cache
          # ensure that after every deployment, CloudFront clears its cached content for all paths (\*), forcing it to fetch the latest version of your files from the S3 bucket.
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
