name: Spring Boot Tests

on:
  push:
    branches: ["main", "dev"] # Run tests on pushes to main or dev branches
    paths: ["employee/**"] # Only run if something in back-end changes
  pull_request:
    branches: ["main", "dev"] # Run tests on pull requests to main or dev branches
    paths: ["employee/**"] # Only run if something in back-end changes

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3 #Speeds up Maven builds by caching dependencies
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run tests
        run: mvn clean verify #Builds and runs all your tests (including E2E)
        working-directory: ./employee # Adjust the working directory to your Spring Boot app folder
